### ISSUE TITLE
Wrong path for normalize

### ISSUE THREAD

**Issue by tomazzaman** [zellwk/adaptivePlaceholders#2]
The second line tries to import from the parent directory, which is commonly *inside* the `bower_components` directory. 

The solution would be either to add another `../` to the path, or remove the `bower_components` part.

**Comment by zellwk** [comment]
Great catch! I have no idea how I missed this one. 

Btw, do you know of a way where I can check whether normalise.scss is already present in user's  project?

**Comment by tomazzaman** [comment]
It seems there's no way currently: https://github.com/sass/sass/issues/139

I would just remove the requirement and *recommend* it in the documentation, but it's your call :)
